# Pandas

In [1]:
# two datatype 
# 1. series
# 2. dataframe

In [13]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("st.csv")
df

     id     name  age gender  marks branch
0     1      Ram   24      m     95  civil
1     2    Shyam   23      m     80    eee
2     3     Sita   20      f     85     cs
3     4    Geeta   21      f     93    eee
4     5    Kamal   18      m     77     me
..  ...      ...  ...    ...    ...    ...
95   96    Sneha   32      f     59    eee
96   97    Sumit   34      m     50  civil
97   98  Aarunya   21      f     88  civil
98   99  Atharva   20      m     90     me
99  100    Kowid   21      m     92  civil

[100 rows x 6 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [11]:
x=[1,2,3,4,5]
a=np.array(x)
a

array([1, 2, 3, 4, 5])

In [12]:
type(a)

numpy.ndarray

In [13]:
a[0]

1

In [14]:
a[3]

4

In [15]:
x=[1,2,3,4,5]

s=pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
type(s)

pandas.core.series.Series

In [17]:
s[0]

1

In [18]:
s[4]

5

In [19]:
# series is 1d labelled array 

x=[1,2,3,4,5]

s=pd.Series(x, index=["a", "b", "c", "d", "e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [21]:
s["a"]

1

In [24]:
s["e"]

5

In [26]:
# df.values

In [27]:
df.head()

   id   name  age gender  marks branch
0   1    Ram   24      m     95  civil
1   2  Shyam   23      m     80    eee
2   3   Sita   20      f     85     cs
3   4  Geeta   21      f     93    eee
4   5  Kamal   18      m     77     me

In [28]:
# | `df.head()`                                         | `df.values`                                |
# | --------------------------------------------------- | ------------------------------------------ |
# | Shows the first 5 rows of a DataFrame (by default). | Returns all the data as a NumPy array.     |
# | Keeps row and column labels.                        | Does **not** include row or column labels. |
# | Used to preview data.                               | Used when you need only the raw values.    |
# | Output is a **DataFrame**.                          | Output is a **NumPy ndarray**.             |

In [2]:
# series -> 1D labelled array 
#dataframe -> 2D labelled array 

# or say 
# dataframe -> collection of series
# series + series -> dataframe

In [18]:
df1 = pd.read_excel("excel1.xlsx")
df1

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,...,away_wickets,away_boundaries,highlights,home_key_batsman,home_key_bowler,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days
0,IPL-2023,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,...,4.0,25.0,Gill's second straight century trumps Kohli's ...,"Virat Kohli,Faf du Plessis","Mohammed Siraj,Harshal Patel","Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match)
1,IPL-2023,1359543,Mumbai Indians v Sunrisers Hyderabad,MI v SRH,"69th Match (D/N), Indian Premier League at Mum...",MI,SRH,MI,BOWL FIRST,200/5,...,5.0,27.0,Green century and Madhwal four-for help Mumbai...,"Cameron Green,Rohit Sharma","Akash Madhwal,Chris Jordan","Ishan Kishan (WK),Rohit Sharma (UKN),Cameron G...","Vivrant Sharma (AR),Mayank Agarwal (UKN),Heinr...","Mayank Agarwal,Vivrant Sharma","Bhuvneshwar Kumar,Mayank Dagar",21 May 2023 - day/night match (20-over match)
2,IPL-2023,1359542,Kolkata Knight Riders v Lucknow Super Giants,KKR v LSG,"68th Match (N), Indian Premier League at Kolka...",KKR,LSG,KKR,BOWL FIRST,176/8,...,8.0,22.0,"Pooran, Bishnoi seal Lucknow Super Giants' pla...","Rinku Singh,Jason Roy","Sunil Narine,Shardul Thakur","Jason Roy (UKN),Venkatesh Iyer (AR),Nitish Ran...","Karan Sharma (AR),Quinton de Kock (WK),Prerak ...","Nicholas Pooran,Quinton de Kock","Ravi Bishnoi,Yash Thakur",20 May 2023 - night match (20-over match)
3,IPL-2023,1359541,Delhi Capitals v Chennai Super Kings,DC v CSK,"67th Match (D/N), Indian Premier League at Del...",DC,CSK,CSK,BAT FIRST,223/3,...,3.0,31.0,"Gaikwad, Conway script CSK's big win. For Delh...","David Warner,Axar Patel","Chetan Sakariya,Anrich Nortje","Prithvi Shaw (UKN),David Warner (UKN),Phil Sal...","Ruturaj Gaikwad (UKN),Devon Conway (UKN),Shiva...","Devon Conway,Ruturaj Gaikwad","Deepak Chahar,Matheesha Pathirana",20 May 2023 - day/night match (20-over match)
4,IPL-2023,1359540,Punjab Kings v Rajasthan Royals,PBKS v RR,"66th Match (N), Indian Premier League at Dhara...",PBKS,RR,RR,BOWL FIRST,187/5,...,6.0,27.0,"Padikkal, Hetmyer keep Royals in the hunt with...","Sam Curran,Jitesh Sharma","Kagiso Rabada,Rahul Chahar","Prabhsimran Singh (UKN),Shikhar Dhawan (UKN),A...","Yashasvi Jaiswal (UKN),Jos Buttler (UKN),Devdu...","Devdutt Padikkal,Yashasvi Jaiswal","Navdeep Saini,Adam Zampa",19 May 2023 - night match (20-over match)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,IPL-2008,336012,Royal Challengers Bangalore v Mumbai Indians,RCB v MI,"55th match (D/N), Indian Premier League at Ben...",RCB,MI,MI,BOWL FIRST,122/9,...,1.0,16.0,Mumbai end IPL campaign with easy win. Mumbai ...,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Mark Boucher (BT),Shreevats Goswami (WK),Misba...","Sanath Jayasuriya (AR),Sachin Tendulkar (BT),R...","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",28 May 2008 - day/night match (20-over match)
1024,IPL-2008,336019,Kings XI Punjab v Rajasthan Royals,KXIP v RR,"56th match (N), Indian Premier League at Mohal...",KXIP,RR,RR,BOWL FIRST,221/3,...,7.0,26.0,Marsh century conquers Rajasthan. Kings XI Pun...,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Shaun Marsh (BT),James Hopes (AR),Yuvraj Singh...","Mohammad Kaif (BT),Niraj Patel (UKN),Younis Kh...","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",28 May 2008 - night match (20-over match)
1025,IPL-2008,336038,Delhi Daredevils v Rajasthan Royals,DC v RR,"1st Semi-Final (N), Indian Premier League at M...",DC,RR,DC,BOWL FIRST,192/9,...,9.0,29.0,Watson helps Rajasthan march into final. This ...,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Gautam Gambhir (BT),Virender Sehwag (BT),Shikh...","Graeme Smith (BT),Swapnil Asnodkar (BT),Sohail...","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",30 May 2008 - night match (20-over match)
1026,IPL-2008,336039,Chennai Super Kings v Kings XI Punjab,CSK v KXIP,"2nd Semi-Final (N), Indian Premier League at M...",CSK,KXIP,KXIP,BAT FIRST,112/8,...,8.0,13.0,Inspired Chennai send Punjab packing. An inspi...,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Shaun Marsh (BT),James Hopes (AR),Kumar Sangak...","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",31 May 2008 - night match (20-over match)
1027,IPL-2008,336040,Chennai Super Kings v Rajasthan Royals,CSK v RR,"Final (N), Indian Premier League at Mumbai, Ju...",CSK,RR,RR,BOWL FIRST,163/5,...,7.0,17.0,Rajasthan champions after cliffhanger. League ...,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Niraj Patel (UKN),Swapnil Asnodkar (BT),Kamran...","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",1 June 2008 - night match (20-over match)

In [21]:
df2 = pd.read_excel("excel1.xlsx", sheet_name="DATA-2")
df2

,SEASON,WINNER,RUNNER UP,PLAYER OF THE MATCH,PLAYER OF THE TOURNAMENT
0,2023,Chennai Super Kings,Gujarat Titians,Devon Conway,Shubman Gill
1,2022,Gujarat Titians,Rajasthan Royals,Hardik Pandya,Jos Butler
2,2021,Chennai Super Kings,Kolkata Knight Riders,Faf du Plessis,Harshal Patel
3,2020,Mumbai Indians,Delhi Capitals,Trent Boult,Jofra Archer
4,2019,Mumbai Indians,Chennai Super Kings,Jasprit Bumrah,Andre Russell
5,2018,Chennai Super Kings,Sunrisers Hyderabad,Shane Watson,Sunil Narine
6,2017,Mumbai Indians,Rising Pune Supergiants,Krunal Pandya,Ben Stokes
7,2016,Sunrisers Hyderabad,Royal Challengers Banglore,Ben Cutting,Virat Kohli
8,2015,Mumbai Indians,Chennai Super Kings,Rohit Sharma,Andre Russell
9,2014,Kolkata Knight Riders,Kings XI Punjab,Manish Pandey,Glenn Maxwell
10,2013,Mumbai Indians,Chennai Super Kings,Kieron Pollard,Shane Watson
11,2012,Kolkata Knight Riders,Chennai Super Kings,Manvinder Bisla,Sunil Narine
12,2011,Chennai Super Kings,Royal Challengers Banglore,Murli Vijay,Chris Gayle
13,2010,Chennai Super Kings,Mumbai Indians,Suresh Raina,Sachin Tendulkar
14,2009,Deccan Chargers,Royal Challengers Banglore,Anil Kumle,Adam Gilchrist
15,2008,Rajasthan Royals,Chennai Super Kings,Yusuf Pathan,Shane Watson

In [22]:
df2["WINNER"][0]

'Chennai Super Kings'

In [24]:
df2["WINNER"][14]

'Deccan Chargers'

In [ ]:
# how to create a dataframe